/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/ui/BaseButton.vue')['default']
    FileGrid: typeof import('./components/FileManager/FileGrid.vue')['default']
    FileSidebar: typeof import('./components/FileManager/FileSidebar.vue')['default']
    FileTable: typeof import('./components/FileManager/FileTable.vue')['default']
    FileToolbar: typeof import('./components/FileManager/FileToolbar.vue')['default']
    FileTree: typeof import('./components/FileManager/FileTree.vue')['default']
    FileView: typeof import('./components/FileManager/FileView.vue')['default']
    HeroShowcase: typeof import('./components/HeroShowcase.vue')['default']
    LoadingSpinner: typeof import('./components/ui/LoadingSpinner.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PasswordInput: typeof import('./components/form/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./components/Toast.vue')['default']
    UserDropdown: typeof import('./components/UserDropdown.vue')['default']
  }
}
